apiVersion: v1
kind: Namespace
metadata:
  name: msockperf
  labels:
    {{- if .Values.rancher.enabled }}
    field.cattle.io/projectId: {{ .Values.rancher.projectId }}
    {{- end }}
  annotations:
    {{- if .Values.rancher.enabled }}
    field.cattle.io/projectId: "{{ .Values.rancher.clusterId }}:{{ .Values.rancher.projectId }}"
    {{- end }}