{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  #annotations:
  labels:
    {{- if .Values.portworx.enabled }}
    pds.portworx.com/available: "false"
    {{- end }}
    {{- if .Values.rancher.enabled }}
    owner: {{ .Values.labels.owner}}
    {{- end }}
{{- end }}
