apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.msockperf.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  endpoints:
    - interval: 15s
      port: web
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.name }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Values.namespace.name }}