apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.msockperf.serviceName }}
  namespace: {{ .Values.Namespace | default "msockperf" }}
  labels:
    app.kubernetes.io/part-of: msockperf-app
  annotations:
    prometheus.io/port: '8082'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: {{ .Values.msockperf.servicePort }}
    targetPort: {{ .Values.msockperf.webPort }}
    protocol: TCP
    name: web 
  selector:
    app: {{ .Values.msockperf.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}